In [1]:
import pandas as pd
import numpy as np

In [2]:
df_mem_topic = pd.read_csv("data/members_topics.csv",index_col='member_id')

/Users/YCheng/anaconda3/lib/python3.6/site-packages/numpy/lib/arraysetops.py:522: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

In [3]:
df_mem_topic.head(10)

           topic_id   topic_key  topic_name
member_id
121483           83  Sports Fan  sportsfans
165644           83  Sports Fan  sportsfans
327482           83  Sports Fan  sportsfans
337743           83  Sports Fan  sportsfans
358259           83  Sports Fan  sportsfans
369808           83  Sports Fan  sportsfans
383024           83  Sports Fan  sportsfans
484925           83  Sports Fan  sportsfans
504385           83  Sports Fan  sportsfans
522784           83  Sports Fan  sportsfans

In [6]:
df_dup = df_mem_topic.drop_duplicates()

In [13]:
df_mem_topic["topic_id"].drop_duplicates()

member_id
121483            83
70613            130
104263           182
19335            183
49200            184
60341            185
6948             206
6                223
311245           225
174531           387
334520           496
962652           505
3944             594
8001             611
22807            644
235880           681
1242650          702
6688             708
10405            728
3402             763
46682            844
49200            862
18613            982
18731           1036
6345            1201
219568          1223
6               1502
23766           1621
26315           1665
815210          1677
              ...
2195610       927032
11973809     1124632
125183952    1181602
216143865    1226012
12635126     1250782
8174709      1268752
223075413    1285972
192628821    1324412
8096822      1338082
58956522     1365962
58956522     1365972
8135911      1374912
232616538    1394712
27384352     1422272
110417092    1431212
11154058     1464752
148710742    1492342
72084122     1493552
8146566      1504609
47133902     1504610
191481155    1504735
216648284    1507371
237476088    1507554
223684294    1510302
217721110    1510610
13668157     1512078
47726242     1514337
68659822     1514354
27355932     1514365
235344943    1514434
Name: topic_id, Length: 1623, dtype: int64

In [7]:
# df_dup['topic_id']
# for i in df_dup['topic_id']:
#     print(i)
df_dup['topic_id'].tolist()

[83,
 130,
 182,
 183,
 184,
 185,
 206,
 223,
 225,
 387,
 496,
 505,
 594,
 611,
 644,
 681,
 702,
 708,
 728,
 763,
 844,
 862,
 982,
 1036,
 1201,
 1223,
 1502,
 1621,
 1665,
 1677,
 1699,
 1849,
 1924,
 1948,
 2039,
 2095,
 2303,
 2369,
 2396,
 3009,
 3066,
 3143,
 3584,
 3586,
 3888,
 3989,
 3998,
 4213,
 4253,
 4422,
 4499,
 6392,
 6613,
 6828,
 7033,
 7117,
 7203,
 7659,
 7670,
 7743,
 7927,
 8476,
 8687,
 9255,
 9696,
 9753,
 9792,
 9859,
 9931,
 9944,
 10050,
 10060,
 10099,
 10122,
 10153,
 10183,
 10209,
 10228,
 10232,
 10249,
 10269,
 10290,
 10306,
 10333,
 10420,
 10451,
 10454,
 10573,
 10574,
 10579,
 10581,
 10923,
 11372,
 12581,
 13349,
 14122,
 14547,
 14657,
 15002,
 15018,
 15028,
 15043,
 15046,
 15073,
 15079,
 15081,
 15115,
 15158,
 15179,
 15197,
 15226,
 15250,
 15254,
 15270,
 15321,
 15322,
 15370,
 15373,
 15374,
 15381,
 15401,
 15405,
 15419,
 15468,
 15479,
 15480,
 15487,
 15489,
 15514,
 15568,
 15635,
 15654,
 15672,
 15681,
 15720,
 15731,
 15767,
 15782,
 15786,
 15813,
 15814,
 15820,
 15904,
 15921,
 15922,
 15923,
 15940,
 15981,
 15987,
 15992,
 16002,
 16049,
 16090,
 16093,
 16094,
 16128,
 16145,
 16162,
 16181,
 16207,
 16216,
 16232,
 16270,
 16277,
 16282,
 16287,
 16305,
 16307,
 16311,
 16326,
 16346,
 16355,
 16372,
 16377,
 16388,
 16389,
 16425,
 16426,
 16440,
 16459,
 16463,
 16505,
 16513,
 16514,
 16517,
 16551,
 16575,
 16594,
 16600,
 16613,
 16614,
 16615,
 16631,
 16672,
 16694,
 16707,
 16714,
 16728,
 16755,
 16789,
 16814,
 16815,
 16859,
 16889,
 16890,
 16967,
 16972,
 17006,
 17013,
 17016,
 17051,
 17106,
 17148,
 17163,
 17176,
 17193,
 17201,
 17205,
 17227,
 17238,
 17311,
 17320,
 17343,
 17344,
 17351,
 17371,
 17411,
 17412,
 17413,
 17437,
 17502,
 17512,
 17544,
 17550,
 17555,
 17558,
 17571,
 17578,
 17595,
 17598,
 17628,
 17658,
 17665,
 17742,
 17760,
 17763,
 17785,
 17818,
 17832,
 17867,
 17873,
 17880,
 17884,
 17885,
 17886,
 17925,
 17929,
 17944,
 17953,
 17962,
 17970,
 17971,
 17986,
 17993,
 17994,
 18071,
 18105,
 18127,
 18145,
 18153,
 18165,
 18167,
 18179,
 18184,
 18189,
 18226,
 18267,
 18268,
 18282,
 18305,
 18315,
 18318,
 18319,
 18341,
 18379,
 18390,
 18427,
 18437,
 18460,
 18473,
 18490,
 18507,
 18510,
 18512,
 18536,
 18558,
 18559,
 18565,
 18571,
 18575,
 18588,
 18590,
 18643,
 18667,
 18668,
 18678,
 18704,
 18714,
 18731,
 18770,
 18771,
 18772,
 18773,
 18784,
 18786,
 18822,
 18823,
 18854,
 18865,
 18881,
 18901,
 18904,
 18914,
 18923,
 18924,
 18931,
 18962,
 18978,
 19003,
 19015,
 19016,
 19036,
 19049,
 19051,
 19066,
 19130,
 19141,
 19144,
 19145,
 19146,
 19167,
 19169,
 19185,
 19202,
 19225,
 19232,
 19253,
 19266,
 19273,
 19283,
 19284,
 19298,
 19323,
 19330,
 19331,
 19350,
 19352,
 19354,
 19355,
 19374,
 19376,
 19384,
 19389,
 19439,
 19451,
 19452,
 19466,
 19471,
 19477,
 19488,
 19496,
 19509,
 19517,
 19518,
 19520,
 19544,
 19548,
 19550,
 19556,
 19585,
 19586,
 19587,
 19594,
 19646,
 19661,
 19733,
 19738,
 19741,
 19743,
 19744,
 19754,
 19763,
 19825,
 19827,
 19872,
 19877,
 19913,
 19954,
 19991,
 19999,
 20006,
 20008,
 20018,
 20033,
 20039,
 20048,
 20052,
 20084,
 20089,
 20093,
 20094,
 20099,
 20148,
 20169,
 20188,
 20242,
 20277,
 20296,
 20301,
 20322,
 20341,
 20395,
 20501,
 20509,
 20519,
 20551,
 20576,
 20591,
 20593,
 20669,
 20694,
 20707,
 20709,
 20752,
 20755,
 20808,
 20810,
 20870,
 20876,
 20884,
 20894,
 20971,
 20972,
 20980,
 20981,
 20987,
 20992,
 21002,
 21011,
 21048,
 21059,
 21108,
 21119,
 21126,
 21130,
 21137,
 21141,
 21155,
 21183,
 21184,
 21259,
 21282,
 21283,
 21290,
 21302,
 21311,
 21355,
 21360,
 21367,
 21416,
 21417,
 21436,
 21437,
 21451,
 21470,
 21488,
 21585,
 21596,
 21683,
 21716,
 21730,
 21755,
 21808,
 21810,
 21827,
 21866,
 21881,
 21899,
 21910,
 21939,
 21940,
 21942,
 21948,
 21953,
 21958,
 21996,
 22033,
 22063,
 22064,
 22065,
 22074,
 22109,
 22115,
 22183,
 22203,
 22208,
 22239,
 22258,
 22268,
 22270,
 22294,
 22307,
 22337,
 22341,
 22382,
 22383,
 22393,
 22394,
 22428,
 22494,
 22514,
 22548,
 22568,
 22571,
 22579,
 22594,
 22606,
 22650,
 22655,
 22660,
 22713,
 22736,
 22765,
 22808,
 22853,
 22854,
 22855,
 22856,
 22878,
 22884,
 22889,
 22900,
 22922,
 22970,
 22993,
 22994,
 22996,
 23006,
 23020,
 23023,
 23027,
 23079,
 23094,
 23103,
 23133,
 23136,
 23153,
 23268,
 23286,
 23314,
 23315,
 23317,
 23329,
 23334,
 23343,
 23347,
 23349,
 23357,
 23364,
 23367,
 23379,
 23380,
 23402,
 23403,
 23413,
 23416,
 23417,
 23428,
 23488,
 23489,
 23492,
 23495,
 23509,
 23524,
 23549,
 23555,
 23572,
 23604,
 23611,
 23621,
 23624,
 23626,
 23629,
 23644,
 23661,
 23669,
 23671,
 23681,
 23695,
 23707,
 23725,
 23734,
 23742,
 23747,
 23748,
 23765,
 23778,
 23791,
 23799,
 23813,
 23852,
 23864,
 23884,
 23889,
 23918,
 23919,
 23945,
 23954,
 23955,
 23956,
 23957,
 23965,
 23974,
 23979,
 23982,
 24018,
 24029,
 24048,
 24060,
 24081,
 24083,
 24111,
 24141,
 24149,
 24156,
 24185,
 24198,
 24200,
 24221,
 24248,
 24259,
 24266,
 24310,
 24314,
 24315,
 24321,
 24322,
 24323,
 24341,
 24349,
 24359,
 24366,
 24373,
 24374,
 24386,
 24387,
 24388,
 24389,
 24400,
 24406,
 24430,
 24449,
 24450,
 24454,
 24480,
 24513,
 24517,
 24531,
 24533,
 24553,
 24555,
 24568,
 24569,
 24570,
 24653,
 24658,
 24711,
 24727,
 24772,
 24775,
 24777,
 24788,
 24828,
 24837,
 24854,
 24860,
 24862,
 24869,
 24883,
 24968,
 24998,
 25004,
 25024,
 25238,
 25261,
 25273,
 25356,
 25439,
 25478,
 25498,
 25526,
 25544,
 25596,
 25623,
 25666,
 25667,
 25698,
 25759,
 25821,
 25822,
 25847,
 25848,
 25849,
 25866,
 25970,
 25999,
 26002,
 26027,
 26036,
 26054,
 26060,
 26082,
 26105,
 26111,
 26113,
 26120,
 26133,
 26157,
 26170,
 26212,
 26217,
 26256,
 26260,
 26276,
 26281,
 26299,
 26324,
 26325,
 26382,
 26389,
 26395,
 26405,
 26406,
 26451,
 26452,
 26524,
 26536,
 26537,
 26567,
 26587,
 26631,
 26642,
 26643,
 26659,
 26660,
 26682,
 26683,
 26701,
 26733,
 26755,
 26788,
 26867,
 26872,
 26894,
 26951,
 26965,
 26985,
 27075,
 27076,
 27079,
 27084,
 27246,
 27248,
 27294,
 27333,
 27365,
 27384,
 27398,
 27416,
 27521,
 27526,
 27603,
 27605,
 27642,
 27701,
 27790,
 27794,
 27870,
 27882,
 27988,
 28061,
 28086,
 28115,
 28120,
 28372,
 28423,
 28424,
 28438,
 28488,
 28589,
 28594,
 28598,
 28612,
 28643,
 28649,
 28718,
 28770,
 28781,
 28806,
 28809,
 28823,
 28834,
 28842,
 28863,
 28976,
 28983,
 28984,
 29057,
 29095,
 29105,
 29234,
 29295,
 29298,
 29308,
 29356,
 29435,
 29436,
 29528,
 29529,
 29557,
 29607,
 29611,
 29654,
 29676,
 29687,
 30003,
 30069,
 30090,
 30093,
 30112,
 30266,
 30273,
 30366,
 30383,
 30547,
 30568,
 30618,
 30635,
 30652,
 30675,
 30849,
 31033,
 31046,
 31054,
 31163,
 31293,
 31319,
 31342,
 31413,
 31536,
 31650,
 31732,
 31757,
 31825,
 31952,
 32260,
 32343,
 32379,
 32390,
 32408,
 32453,
 32550,
 32800,
 32932,
 32968,
 32995,
 32996,
 33003,
 33113,
 33211,
 33284,
 33428,
 33468,
 33503,
 33577,
 33600,
 33601,
 33618,
 33709,
 33803,
 33947,
 34050,
 34202,
 34213,
 34267,
 34352,
 34358,
 34374,
 34376,
 34378,
 34410,
 34540,
 34542,
 34666,
 34667,
 34716,
 34719,
 34808,
 34918,
 34978,
 35009,
 35071,
 35171,
 35211,
 35244,
 35275,
 35414,
 35470,
 35499,
 35535,
 35588,
 35807,
 35826,
 35844,
 35877,
 35929,
 36014,
 36017,
 36030,
 36246,
 36403,
 36447,
 36451,
 36550,
 36704,
 36726,
 36733,
 36811,
 36850,
 37166,
 37217,
 37275,
 37276,
 37479,
 37556,
 37659,
 37662,
 37755,
 37891,
 37931,
 38020,
 38026,
 38265,
 38275,
 38307,
 38327,
 38425,
 38585,
 38591,
 38632,
 38658,
 38777,
 38920,
 39059,
 39072,
 39085,
 39256,
 39288,
 39289,
 39440,
 39578,
 39765,
 39861,
 39871,
 39879,
 39880,
 40114,
 40115,
 40126,
 40190,
 40215,
 40266,
 40392,
 40424,
 40739,
 40742,
 40838,
 40874,
 40885,
 40913,
 40914,
 40938,
 40983,
 41087,
 41129,
 41269,
 41370,
 41481,
 41556,
 41560,
 ...]

In [8]:
group = df_mem_topic.groupby(by=['member_id'])

In [9]:
group.size()

member_id
6             9
36            1
210           1
848           2
1230          5
1581          3
1945          3
2629          3
3045          4
3402          1
3588          3
3705          1
3944          5
4368          9
4728          2
6345          7
6688          6
6948          3
7001          8
8001          2
8013          1
9356         16
10405         7
10448         1
10548         2
10600         6
11053         2
11266         2
11884         6
13511         2
             ..
240808127    13
240808558    22
240809400     3
240810899    18
240811360    17
240811542     8
240811711     8
240811847     5
240812317     4
240813099     1
240813639     5
240816189     4
240817162     1
240817878     6
240818081     2
240819321     7
240820767    13
240823125     6
240830739    10
240833111     1
240837395    10
240838597    14
240838614     1
240840580    22
240841318     6
240842680     3
240842986     1
240845614     9
240849026     3
240852081     6
Length: 605790, dtype: int64

In [ ]:
group_topic = df_mem_topic.groupby(by=['topic_id'])
group_topic.size().to_frame('size')['size'].tolist()

In [ ]:
group_topic.size()
group_topic.size().to_frame('size')['size'].tolist()

In [ ]:
group_topic['topic_id']['83']

In [ ]:
topic_corr = np.zeros(1623*1623).reshape(1623,1623)
topic_corr.shape

In [ ]:
df_dup = df_mem_topic.drop_duplicates()
topic_lst = df_dup['topic_id'].tolist()

In [ ]:
group_topic = df_mem_topic.groupby(by=['topic_id'])
topic_member_lst = group_topic.size().to_frame('size')['size'].tolist()

## This Step

In [ ]:
for i in range(1623):
#     print(i)
    topic_a = topic_lst[i]
    for j in range(1623 - i):
        print("_____START_____")
        print(i)
        print (j + i)
        topic_b = topic_lst[j + i]
        df_mem_topic[df_mem_topic.topic_id == topic_a]
        common_member_cnt = len(pd.merge(df_mem_topic[df_mem_topic.topic_id == topic_a], df_mem_topic[df_mem_topic.topic_id == topic_b], how='inner', on=['member_id']))
#         print(common_member_cnt)
        cor_val = common_member_cnt * common_member_cnt /(topic_member_lst[i] * topic_member_lst[j + i])
#         print(cor_val)
        print("_____END_____")
        topic_corr[i][j + i] = cor_val
np.save("corr_result.npy", topic_corr)